a = int(input())
b = int(input())
print("The Addition of two numbers is:", a+b)
print("The Subtraction of two numbers is:",  a-b)
print("The Multiplication of two numbers is:",  a*b)
print("The Division of two numbers is:",  a/b)
print("The Modulus Division of two numbers is:", a%b)
print("The Floor Division of two numbers is:", a//b)
print("The Exponentation of two numbers is:" , a**b)
